// <auto-generated />
using System;
using Infraestructura.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entities.AuditoriaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DetalleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditoriaLogs", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("SaldoRetenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Billeteras", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SaldoRetenido = 0m,
                            SaldoTotal = 0m,
                            UsuarioId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            SaldoRetenido = 45000m,
                            SaldoTotal = 150000m,
                            UsuarioId = 2,
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            SaldoRetenido = 0m,
                            SaldoTotal = 200000m,
                            UsuarioId = 3,
                            Version = 1
                        },
                        new
                        {
                            Id = 4,
                            SaldoRetenido = 0m,
                            SaldoTotal = 500m,
                            UsuarioId = 4,
                            Version = 1
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlIcono")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tecnología",
                            UrlIcono = "tech.png"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Coleccionables",
                            UrlIcono = "col.png"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Indumentaria",
                            UrlIcono = "ropa.png"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Vehículos",
                            UrlIcono = "auto.png"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Puja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPuja")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubastaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("SubastaId");

                    b.ToTable("Pujas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompradorId = 3,
                            FechaPuja = new DateTime(2026, 8, 30, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            Monto = 35000m,
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompradorId = 2,
                            FechaPuja = new DateTime(2026, 8, 30, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            Monto = 45000m,
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 3,
                            CompradorId = 3,
                            FechaPuja = new DateTime(2026, 8, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 25000m,
                            SubastaId = 4
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IncrementoMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Subastas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Subasta activa estándar",
                            Estado = "Activa",
                            FechaFin = new DateTime(2026, 8, 30, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2026, 8, 30, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IncrementoMinimo = 1000m,
                            PrecioBase = 30000m,
                            Titulo = "Notebook Pro",
                            UrlImagen = "img1.png",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descripcion = "Subasta crítica para probar anti-sniping",
                            Estado = "Activa",
                            FechaFin = new DateTime(2026, 8, 30, 12, 1, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2026, 8, 30, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IncrementoMinimo = 500m,
                            PrecioBase = 10000m,
                            Titulo = "Reloj Antiguo",
                            UrlImagen = "img2.png",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 4,
                            Descripcion = "Subasta programada",
                            Estado = "Programada",
                            FechaFin = new DateTime(2026, 9, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2026, 8, 31, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IncrementoMinimo = 50000m,
                            PrecioBase = 1500000m,
                            Titulo = "Auto Usado",
                            UrlImagen = "img3.png",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Descripcion = "Subasta vencida con ganador",
                            Estado = "Activa",
                            FechaFin = new DateTime(2026, 8, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2026, 8, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IncrementoMinimo = 1000m,
                            PrecioBase = 20000m,
                            Titulo = "Monitor 24",
                            UrlImagen = "img4.png",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 3,
                            Descripcion = "Subasta vencida sin ofertas",
                            Estado = "Activa",
                            FechaFin = new DateTime(2026, 8, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2026, 8, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IncrementoMinimo = 2000m,
                            PrecioBase = 50000m,
                            Titulo = "Campera Cuero",
                            UrlImagen = "img5.png",
                            VendedorId = 1,
                            Version = 1
                        });
                });

            modelBuilder.Entity("Dominio.Entities.TransaccionLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilleteraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SubastaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.HasIndex("SubastaId");

                    b.ToTable("TransaccionesLedger", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BilleteraId = 2,
                            Fecha = new DateTime(2026, 8, 26, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 150000m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 2,
                            BilleteraId = 2,
                            Fecha = new DateTime(2026, 8, 30, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            Monto = 45000m,
                            SubastaId = 1,
                            Tipo = "Retencion"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "vendedor@test.com",
                            FechaRegistro = new DateTime(2026, 8, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Vendedor",
                            PasswordHash = "hash123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "comprador1@test.com",
                            FechaRegistro = new DateTime(2026, 8, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Comprador 1",
                            PasswordHash = "hash123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "comprador2@test.com",
                            FechaRegistro = new DateTime(2026, 8, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Comprador 2",
                            PasswordHash = "hash123"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sinfondos@test.com",
                            FechaRegistro = new DateTime(2026, 8, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sin Fondos",
                            PasswordHash = "hash123"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.AuditoriaLog", b =>
                {
                    b.HasOne("Dominio.Entities.Usuario", "Usuario")
                        .WithMany("AuditoriaLogs")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dominio.Entities.Billetera", b =>
                {
                    b.HasOne("Dominio.Entities.Usuario", "Usuario")
                        .WithOne("Billetera")
                        .HasForeignKey("Dominio.Entities.Billetera", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dominio.Entities.Puja", b =>
                {
                    b.HasOne("Dominio.Entities.Usuario", "Comprador")
                        .WithMany("Pujas")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Subasta", "Subasta")
                        .WithMany("Pujas")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Dominio.Entities.Subasta", b =>
                {
                    b.HasOne("Dominio.Entities.Categoria", "Categoria")
                        .WithMany("Subastas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Usuario", "Vendedor")
                        .WithMany("Subastas")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Dominio.Entities.TransaccionLedger", b =>
                {
                    b.HasOne("Dominio.Entities.Billetera", "Billetera")
                        .WithMany("Transacciones")
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Subasta", "Subasta")
                        .WithMany("Transacciones")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Billetera");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Dominio.Entities.Billetera", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("Dominio.Entities.Categoria", b =>
                {
                    b.Navigation("Subastas");
                });

            modelBuilder.Entity("Dominio.Entities.Subasta", b =>
                {
                    b.Navigation("Pujas");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("Dominio.Entities.Usuario", b =>
                {
                    b.Navigation("AuditoriaLogs");

                    b.Navigation("Billetera");

                    b.Navigation("Pujas");

                    b.Navigation("Subastas");
                });
#pragma warning restore 612, 618
        }
    }
}
